# Generated by Django 4.2 on 2023-04-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
